/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_ferrand_chunky_jpegxl_JpegxlWriter */

#ifndef _Included_dev_ferrand_chunky_jpegxl_JpegxlWriter
#define _Included_dev_ferrand_chunky_jpegxl_JpegxlWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_ferrand_chunky_jpegxl_JpegxlWriter
 * Method:    compressInMemory
 * Signature: (II[I)J
 */
JNIEXPORT jlong JNICALL Java_dev_ferrand_chunky_jpegxl_JpegxlWriter_compressInMemory
  (JNIEnv *, jclass, jint, jint, jintArray, jfloat);

/*
 * Class:     dev_ferrand_chunky_jpegxl_JpegxlWriter
 * Method:    readSomeCompressed
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_dev_ferrand_chunky_jpegxl_JpegxlWriter_readSomeCompressed
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     dev_ferrand_chunky_jpegxl_JpegxlWriter
 * Method:    freeCompressed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_ferrand_chunky_jpegxl_JpegxlWriter_freeCompressed
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}

#endif
#endif
